// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleCowApi.Data;

#nullable disable

namespace SimpleCowApi.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("SimpleCowApi.Data.Models.Cow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FarmId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.ToTable("Cows");

                    b.HasData(
                        new
                        {
                            Id = 20001,
                            Age = 4,
                            FarmId = 10001,
                            Name = "Bessie"
                        },
                        new
                        {
                            Id = 20002,
                            Age = 2,
                            FarmId = 10002,
                            Name = "MooMoo"
                        },
                        new
                        {
                            Id = 20003,
                            Age = 3,
                            Name = "Daisy"
                        });
                });

            modelBuilder.Entity("SimpleCowApi.Data.Models.Farm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Farms");

                    b.HasData(
                        new
                        {
                            Id = 10001,
                            Location = "Texas",
                            Name = "Sunny Pastures"
                        },
                        new
                        {
                            Id = 10002,
                            Location = "Kansas",
                            Name = "Green Valley Ranch"
                        });
                });

            modelBuilder.Entity("SimpleCowApi.Data.Models.Cow", b =>
                {
                    b.HasOne("SimpleCowApi.Data.Models.Farm", "Farm")
                        .WithMany()
                        .HasForeignKey("FarmId");

                    b.Navigation("Farm");
                });
#pragma warning restore 612, 618
        }
    }
}
